package:
  name: blackboxphaseopt
  version: "0.1.0"

source:
  path: ..

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python=3.13.3
    - pip
    - setuptools
  run:
    - python=3.13.3
    - numpy=2.3.5
    - conda-forge::heyoka.py=7.8.1
    - gurobi::gurobi=12.0.3
    - jax=0.7.2

test:
  imports:
    - blackboxphaseopt

about:
  home: https://github.com/Malav-P/blackboxphaseopt
  summary: "Brief description"
  license: MIT